#!/bin/sh
#
# @name gazebo-classic_neverlost_livox_pitch30
#
# @type Quadrotor X
#
# @maintainer yzy
#

. ${R}etc/init.d/rc.mc_defaults


param set-default CA_AIRFRAME 0

param set-default COM_RCL_EXCEPT 4
param set-default NAV_DLL_ACT 0
param set-default NAV_RCL_ACT 0

param set-default EKF2_EV_DELAY 5
param set-default EKF2_EV_CTRL 11
param set-default EKF2_HGT_REF 3
param set-default EKF2_GPS_CTRL 0
param set-default EKF2_EV_POS_Z -0.15
param set-default EKF2_EVP_GATE 8.0
param set-default EKF2_EVP_NOISE 0.02
param set-default EKF2_EV_NOISE_MD 1
param set-default ATT_EXT_HDG_M 1

param set-default EKF2_MAG_CHECK 0
param set-default EKF2_MAG_TYPE 5
param set-default CA_ROTOR_COUNT 4
param set-default CA_ROTOR0_PX 0.08838
param set-default CA_ROTOR0_PY 0.08838
param set-default CA_ROTOR0_KM 0.05
param set-default CA_ROTOR1_PX -0.08838
param set-default CA_ROTOR1_PY -0.08838
param set-default CA_ROTOR1_KM 0.05
param set-default CA_ROTOR2_PX 0.08838
param set-default CA_ROTOR2_PY -0.08838
param set-default CA_ROTOR2_KM -0.05
param set-default CA_ROTOR3_PX -0.08838
param set-default CA_ROTOR3_PY 0.08838
param set-default CA_ROTOR3_KM -0.05

param set-default PWM_MAIN_FUNC1 101
param set-default PWM_MAIN_FUNC2 102
param set-default PWM_MAIN_FUNC3 103
param set-default PWM_MAIN_FUNC4 104

param set-default MC_ROLLRATE_K 0.5
param set-default MC_ROLLRATE_D 0.005
param set-default MC_ROLLRATE_I 0.1

param set-default MC_PITCHRATE_K 0.5
param set-default MC_PITCHRATE_D 0.005
param set-default MC_PITCHRATE_I 0.1

param set-default MC_YAWRATE_K 0.5
param set-default MC_YAWRATE_I 0.1


param set-default SDLOG_PROFILE 899
param set-default SDLOG_MODE 0

param set-default SYS_HAS_GPS 0
param set-default SYS_HAS_MAG 0
